'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Buscador_Informes_SistemaRegistroGestiones

    '''<summary>
    '''lblTitulo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo_Informe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNombre_Funcionario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombre_Funcionario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTipo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipo_Informe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTitulo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitulo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNombre_Funcionario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre_Funcionario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo_Informe As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBuscar_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar_Informe As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCharges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvwInforme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwInforme As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsGridview_Informes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsGridview_Informes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkFalso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFalso As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mpeDetalles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDetalles As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPop_Id_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPop_Id_Informe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPop_Id_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Id_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Titulo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Titulo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Empleado_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Empleado_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Tipo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Tipo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Num_Oficio_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Num_Oficio_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Aprobacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Aprobacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Culminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Culminacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Traslado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Traslado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Avance_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Avance_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Remitido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Remitido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Hallazgo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Hallazgo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Recomendaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Recomendaciones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Observaciones_Generales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Observaciones_Generales As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCerrar_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Modal As Global.System.Web.UI.WebControls.Button
End Class
