'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Menu_Principal

    '''<summary>
    '''imbBtn_Gestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbBtn_Gestion As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbBtn_DAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbBtn_DAU As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbBtn_DMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbBtn_DMC As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblGestion_Servicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGestion_Servicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtencion_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtencion_Usuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMejora_Continua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMejora_Continua As Global.System.Web.UI.WebControls.Label
End Class
