'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Modificar_Gestiones

    '''<summary>
    '''lblCodigo_Gestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigo_Gestion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtId_Gestiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtId_Gestiones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTipo_Gestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipo_Gestion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblTipo_Gestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTipo_Gestion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblCedula_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCedula_Usuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNombre_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombre_Usuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecha_Ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha_Ingreso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCedula_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCedula_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNombre_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFecha_Ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecha_Ingreso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFuncionario_Tramita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuncionario_Tramita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConfidencialidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfidencialidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFuente_Generadora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuente_Generadora As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''intIdEmpleados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents intIdEmpleados As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sdsEmpleados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsEmpleados As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlConfidencialidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConfidencialidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFuente_Generadora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFuente_Generadora As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTipo_Servicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipo_Servicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDireccion_Regional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDireccion_Regional As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSupervision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupervision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipo_Servicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo_Servicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_Direccion_Regional_Educacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Direccion_Regional_Educacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSupervision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSupervision As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblNombre_CE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombre_CE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescripcion_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion_Unidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumero_Oficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumero_Oficio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNombre_CE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre_CE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDescripcion_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDescripcion_Unidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sdsDescripcion_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDescripcion_Unidad As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtNumero_Oficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumero_Oficio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDescripcion_Despacho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion_Despacho As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescripcion_Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion_Direccion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescripcion_Departamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion_Departamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDespacho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDespacho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDireccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDimension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLetra_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLetra_Dimension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetalle_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetalle_Dimension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipo_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo_Dimension As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sdsTipo_Dimensiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsTipo_Dimensiones As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlLetra_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLetra_Dimension As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sdsLetra_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsLetra_Dimension As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtTipo_Detalle_Letra_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipo_Detalle_Letra_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTipo_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipo_Usuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipo_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo_Usuario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategoria As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetalle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAsunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsunto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRespuesta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRespuesta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkDummy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDummy As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ModalPopupExtender_Exito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender_Exito As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup_Exito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup_Exito As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnCerrar_Exito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Exito As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtender_Incompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender_Incompleto As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup_Incompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup_Incompleto As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnCerrar_Incompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Incompleto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ModalPopupExtender_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender_Error As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnCerrar_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Error As Global.System.Web.UI.WebControls.Button
End Class
