'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tabla_Informes

    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBorrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBorrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBuscador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscador As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBitacora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBitacora As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cbeConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbeConfirmacion As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''mpeConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeConfirmacion As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''PanelConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelConfirmacion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanelTabla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelTabla As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grdCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCharges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvwInforme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwInforme As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsGridview_Informes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsGridview_Informes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lnkFalso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFalso As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mpeDetalles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDetalles As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPop_Id_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPop_Id_Informe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPop_Id_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Id_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Titulo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Titulo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Empleado_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Empleado_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Tipo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Tipo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Num_Oficio_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Num_Oficio_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Aprobacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Aprobacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Culminacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Culminacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Traslado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Traslado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Avance_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Avance_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Remitido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Remitido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Hallazgo_Informe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Hallazgo_Informe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Recomendaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Recomendaciones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Observaciones_Generales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Observaciones_Generales As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCerrar_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Modal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dummylink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dummylink1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ModalPopupExtender_Borrar_No_Permiso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender_Borrar_No_Permiso As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup_NoPermiso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup_NoPermiso As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCerrar_NoPermiso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_NoPermiso As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dummylink2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dummylink2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ModalPopupExtender_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtender_Error As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup_Error As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCerrar_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Error As Global.System.Web.UI.WebControls.Button
End Class
