'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tabla_Gestiones

    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBorrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBorrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBuscar_TipoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar_TipoGestion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBitacora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBitacora As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grdCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCharges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvwGestiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwGestiones As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsGridView_Gestiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsGridView_Gestiones As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lnkFalso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFalso As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mpeDetalles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDetalles As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPop_Id_Gestiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPop_Id_Gestiones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSPop_Id_Gestiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSPop_Id_Gestiones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Tipo_Gestiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Tipo_Gestiones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Cedula_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Cedula_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Nombre_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Nombre_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Ingreso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Confidencialida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Confidencialida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Supervision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Supervision As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fuente_Generadora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fuente_Generadora As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Tipo_Servicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Tipo_Servicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Empleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Empleado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Regional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Regional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_CE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_CE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Unidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Despacho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Despacho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Direccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Departamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Departamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Letra_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Letra_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Detalle_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Detalle_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Num_Oficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Num_Oficio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Tipo_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Tipo_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Detalle_Gestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Detalle_Gestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Respuesta_Gestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Respuesta_Gestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCerrar_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Modal As Global.System.Web.UI.WebControls.Button
End Class
