'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tabla_Casos

    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBorrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBorrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVolver As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBuscador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscador As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCharges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvwCasos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwCasos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sdsGridView_Casos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsGridView_Casos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lnkFalso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFalso As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mpeDetalles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDetalles As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPop_Id_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPop_Id_Caso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPop_Id_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Id_Caso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Num_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Num_Caso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Estado_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Estado_Caso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Caso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Cedula_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Cedula_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Nombre_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Nombre_Usuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Empleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Empleado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_CE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_CE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Unidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Despacho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Despacho As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Direccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Departamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Departamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Letra_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Letra_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Detalle_Dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Detalle_Dimension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Num_Oficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Num_Oficio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Oficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Oficio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Condicion_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Condicion_Caso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Detalle_Inconformidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Detalle_Inconformidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Respuesta_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Respuesta_Caso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Respuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Respuesta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Valoracion_Admisibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Valoracion_Admisibilidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Veredicto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Veredicto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Trazabilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Trazabilidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPop_Fecha_Cerrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPop_Fecha_Cerrado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnExportar_Word control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportar_Word As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCerrar_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrar_Modal As Global.System.Web.UI.WebControls.Button
End Class
